// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVVAWc8I_1j9CUP4uLbUncitQPKFzqdCM',
    appId: '1:1010670963181:web:e8eb49652d54b2583effe4',
    messagingSenderId: '1010670963181',
    projectId: 'online-store-686a0',
    authDomain: 'online-store-686a0.firebaseapp.com',
    storageBucket: 'online-store-686a0.firebasestorage.app',
    measurementId: 'G-ZT2TM801S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcLtZmhnCg3XOOt51ZQm4kDIPS1ZTuPS8',
    appId: '1:1010670963181:android:13c29f153f70824a3effe4',
    messagingSenderId: '1010670963181',
    projectId: 'online-store-686a0',
    storageBucket: 'online-store-686a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopYE7TemWW0tcpriPxiCo0qeDha1Aqh8',
    appId: '1:1010670963181:ios:69445c45866d542a3effe4',
    messagingSenderId: '1010670963181',
    projectId: 'online-store-686a0',
    storageBucket: 'online-store-686a0.firebasestorage.app',
    iosBundleId: 'com.example.tstoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDopYE7TemWW0tcpriPxiCo0qeDha1Aqh8',
    appId: '1:1010670963181:ios:69445c45866d542a3effe4',
    messagingSenderId: '1010670963181',
    projectId: 'online-store-686a0',
    storageBucket: 'online-store-686a0.firebasestorage.app',
    iosBundleId: 'com.example.tstoreApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVVAWc8I_1j9CUP4uLbUncitQPKFzqdCM',
    appId: '1:1010670963181:web:ba599fb1a5f56d153effe4',
    messagingSenderId: '1010670963181',
    projectId: 'online-store-686a0',
    authDomain: 'online-store-686a0.firebaseapp.com',
    storageBucket: 'online-store-686a0.firebasestorage.app',
    measurementId: 'G-4VWQ5YG63N',
  );
}
